package tts

import (
	"bytes"
	"context"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// ── Constants ─────────────────────────────────────────────────────────────────

const (
	// MaxSpeedupPercent is the maximum TTS speed-up percentage (Tier 1).
	// At +25%, speech sounds natural without noticeable distortion.
	MaxSpeedupPercent = 25

	// MaxStretchPercent is the maximum DSP time-stretch percentage (Tier 2).
	// Beyond +15%, artifacts become audible with phase vocoder.
	MaxStretchPercent = 15

	// FFmpegTimeout is the maximum time allowed for a single FFmpeg operation.
	FFmpegTimeout = 5 * time.Minute

	// DefaultCharsPerSecond is the Vietnamese speech rate for duration estimation.
	DefaultCharsPerSecond = 15.0

	// fadeDuration is the fade-out duration in seconds for overflow fallback.
	fadeDuration = 0.5

	// fadeMinMs is the minimum fade-out in milliseconds for the overflow strategy.
	fadeMinMs = 200
)

// ── Public API ────────────────────────────────────────────────────────────────

// AlignAudioToWindow adjusts audio duration to fit within the target window.
// Returns the path to the aligned audio file.
//
// Two-tier strategy (ported from python-worker/utils/audio.py):
//   Tier 1 (rate): FFmpeg atempo filter (max +25%, natural sounding).
//   Tier 2 (stretch): FFmpeg rubberband filter (max +15%, phase vocoder, preserves pitch).
//   Fallback: Trim + fade-out if audio is still too long after both tiers.
//
// Parameters:
//   - audioPath: path to the source audio file (generated by Edge TTS)
//   - targetDuration: target duration in seconds
//   - tmpDir: directory for intermediate aligned files
//
// Returns the path to the aligned audio file (may be the same as audioPath if
// no alignment was needed).
func AlignAudioToWindow(audioPath string, targetDuration float64, tmpDir string) (string, error) {
	if targetDuration <= 0 {
		return "", fmt.Errorf("target duration must be positive, got %f", targetDuration)
	}

	// 1. Get current audio duration.
	currentDur, err := GetAudioDuration(audioPath)
	if err != nil {
		return "", fmt.Errorf("get audio duration: %w", err)
	}

	// No alignment needed if audio is already within the window.
	if currentDur <= targetDuration {
		return audioPath, nil
	}

	ratio := currentDur / targetDuration
	maxSpeedup := 1.0 + float64(MaxSpeedupPercent)/100.0

	// 2. Tier 1: Use atempo filter (max +25%).
	if ratio <= maxSpeedup {
		outputPath := filepath.Join(tmpDir, "aligned_t1.mp3")
		err := ffmpegAtempo(audioPath, outputPath, ratio)
		if err != nil {
			return "", fmt.Errorf("tier 1 atempo alignment failed: %w", err)
		}
		return outputPath, nil
	}

	// 3. Tier 2: Chain atempo + rubberband for maximum compression.
	remaining := ratio / maxSpeedup
	remainingPct := (remaining - 1.0) * 100.0
	maxStretch := float64(MaxStretchPercent)

	if remainingPct <= maxStretch {
		// Step 1: Apply max atempo.
		tier1Path := filepath.Join(tmpDir, "aligned_t1.mp3")
		err := ffmpegAtempo(audioPath, tier1Path, maxSpeedup)
		if err != nil {
			return "", fmt.Errorf("tier 2: atempo step failed: %w", err)
		}

		// Step 2: Apply rubberband for remaining stretch.
		outputPath := filepath.Join(tmpDir, "aligned_t2.mp3")
		err = ffmpegRubberband(tier1Path, outputPath, remaining)
		if err != nil {
			return "", fmt.Errorf("tier 2: rubberband step failed: %w", err)
		}
		return outputPath, nil
	}

	// 4. Fallback: Cut + fade-out.
	outputPath := filepath.Join(tmpDir, "aligned_fallback.mp3")
	err = ffmpegTrimFade(audioPath, outputPath, targetDuration)
	if err != nil {
		return "", fmt.Errorf("fallback trim+fade failed: %w", err)
	}
	return outputPath, nil
}

// ConcatAudioSegments joins multiple audio files into one continuous MP3
// using the FFmpeg concat demuxer.
//
// Parameters:
//   - segmentPaths: ordered list of audio file paths to concatenate
//   - outputPath: path for the concatenated output file
//
// Timeout: FFmpegTimeout per invocation.
func ConcatAudioSegments(segmentPaths []string, outputPath string) error {
	if len(segmentPaths) == 0 {
		return fmt.Errorf("no segments to concatenate")
	}

	if len(segmentPaths) == 1 {
		// Single segment — just copy.
		return copyFile(segmentPaths[0], outputPath)
	}

	// Create a temporary concat file listing all segments.
	concatDir := filepath.Dir(outputPath)
	concatFile, err := os.CreateTemp(concatDir, "concat_*.txt")
	if err != nil {
		return fmt.Errorf("create concat file: %w", err)
	}
	defer os.Remove(concatFile.Name())

	var buf bytes.Buffer
	for _, p := range segmentPaths {
		absPath, err := filepath.Abs(p)
		if err != nil {
			return fmt.Errorf("resolve path %s: %w", p, err)
		}
		// FFmpeg concat demuxer expects "file '/path/to/file'"
		buf.WriteString(fmt.Sprintf("file '%s'\n", absPath))
	}

	if _, err := concatFile.Write(buf.Bytes()); err != nil {
		concatFile.Close()
		return fmt.Errorf("write concat file: %w", err)
	}
	concatFile.Close()

	// Run ffmpeg concat.
	ctx, cancel := context.WithTimeout(context.Background(), FFmpegTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, "ffmpeg",
		"-f", "concat",
		"-safe", "0",
		"-i", concatFile.Name(),
		"-c", "copy",
		outputPath,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ffmpeg concat failed: %w, stderr: %s", err, truncateString(stderr.String(), 500))
	}

	// Verify output.
	if info, err := os.Stat(outputPath); err != nil || info.Size() == 0 {
		return fmt.Errorf("concat output %s is missing or empty", outputPath)
	}

	return nil
}

// GetAudioDuration returns the duration of an audio file in seconds using ffprobe.
func GetAudioDuration(filePath string) (float64, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "ffprobe",
		"-v", "error",
		"-show_entries", "format=duration",
		"-of", "default=noprint_wrappers=1:nokey=1",
		filePath,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return 0, fmt.Errorf("ffprobe failed for %s: %w, stderr: %s",
			filePath, err, truncateString(stderr.String(), 200))
	}

	durationStr := strings.TrimSpace(stdout.String())
	if durationStr == "" {
		return 0, fmt.Errorf("ffprobe returned empty duration for %s", filePath)
	}

	duration, err := strconv.ParseFloat(durationStr, 64)
	if err != nil {
		return 0, fmt.Errorf("parse duration %q: %w", durationStr, err)
	}

	return duration, nil
}

// ── Internal FFmpeg Helpers ──────────────────────────────────────────────────

// ffmpegAtempo applies FFmpeg's atempo filter to speed up or slow down audio.
// ratio: 1.0 = no change, >1.0 = speed up, <1.0 = slow down.
// FFmpeg atempo supports 0.5–2.0, but for cascading we stay in 0.5–2.0.
func ffmpegAtempo(inputPath, outputPath string, ratio float64) error {
	if ratio <= 0 {
		return fmt.Errorf("atempo ratio must be positive, got %f", ratio)
	}

	// Clamp ratio to [0.5, 2.0] — FFmpeg atempo limit.
	if ratio < 0.5 {
		ratio = 0.5
	}
	if ratio > 2.0 {
		ratio = 2.0
	}

	ratioStr := strconv.FormatFloat(ratio, 'f', 3, 64)

	ctx, cancel := context.WithTimeout(context.Background(), FFmpegTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, "ffmpeg",
		"-y",
		"-i", inputPath,
		"-filter:a", fmt.Sprintf("atempo=%s", ratioStr),
		"-q:a", "2", // High quality VBR MP3
		outputPath,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ffmpeg atempo=%.3f failed: %w, stderr: %s",
			ratio, err, truncateString(stderr.String(), 500))
	}

	// Verify output.
	if info, err := os.Stat(outputPath); err != nil || info.Size() == 0 {
		return fmt.Errorf("atempo output %s is missing or empty", outputPath)
	}

	return nil
}

// ffmpegRubberband applies FFmpeg's rubberband filter (phase vocoder) for
// time-stretching without pitch change.
// stretchRatio: e.g. 0.12 = speed up by 12%.
func ffmpegRubberband(inputPath, outputPath string, stretchRatio float64) error {
	if stretchRatio <= 0 {
		return fmt.Errorf("rubberband stretch ratio must be positive, got %f", stretchRatio)
	}

	// Convert stretch ratio to tempo factor.
	// rubberband tempo: 1.0 = no change, >1.0 = speed up, <1.0 = slow down.
	// A stretch ratio of 0.12 means we need to play at 1.12x speed.
	tempoFactor := 1.0 + stretchRatio

	// Clamp tempo to reasonable range (rubberband supports 0.5–2.0).
	if tempoFactor < 0.5 {
		tempoFactor = 0.5
	}
	if tempoFactor > 2.0 {
		tempoFactor = 2.0
	}

	tempoStr := strconv.FormatFloat(tempoFactor, 'f', 3, 64)

	ctx, cancel := context.WithTimeout(context.Background(), FFmpegTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, "ffmpeg",
		"-y",
		"-i", inputPath,
		"-filter:a", fmt.Sprintf("rubberband=tempo=%s", tempoStr),
		"-q:a", "2",
		outputPath,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ffmpeg rubberband tempo=%.3f failed: %w, stderr: %s",
			tempoFactor, err, truncateString(stderr.String(), 500))
	}

	if info, err := os.Stat(outputPath); err != nil || info.Size() == 0 {
		return fmt.Errorf("rubberband output %s is missing or empty", outputPath)
	}

	return nil
}

// ffmpegTrimFade trims audio to targetDuration with a smooth fade-out at the end.
// This is the fallback strategy when 2-tier alignment is insufficient.
func ffmpegTrimFade(inputPath, outputPath string, targetDuration float64) error {
	// Fade starts fadeDuration before the end.
	fadeStart := math.Max(0, targetDuration-fadeDuration)
	startStr := strconv.FormatFloat(fadeStart, 'f', 3, 64)
	durStr := strconv.FormatFloat(targetDuration, 'f', 3, 64)

	ctx, cancel := context.WithTimeout(context.Background(), FFmpegTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, "ffmpeg",
		"-y",
		"-i", inputPath,
		"-ss", "0",
		"-t", durStr,
		"-af", fmt.Sprintf("afade=t=out:st=%s:d=%.3f", startStr, fadeDuration),
		"-q:a", "2",
		outputPath,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ffmpeg trim+fade failed: %w, stderr: %s",
			err, truncateString(stderr.String(), 500))
	}

	if info, err := os.Stat(outputPath); err != nil || info.Size() == 0 {
		return fmt.Errorf("trim+fade output %s is missing or empty", outputPath)
	}

	return nil
}

// ── General Helpers ──────────────────────────────────────────────────────────

// copyFile copies a file from src to dst using an OS-level copy (not FFmpeg).
func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return fmt.Errorf("read source %s: %w", src, err)
	}
	if err := os.WriteFile(dst, data, 0644); err != nil {
		return fmt.Errorf("write destination %s: %w", dst, err)
	}
	return nil
}
